declare namespace cocoascript {
  /**
   * An object that contains information about an input action, such as a mouse click or a key press.
   * doc://com.apple.documentation/documentation/appkit/nsevent
   */
  interface NSEvent extends NSObject {
    // doc://com.apple.documentation/documentation/appkit/nsevent/1528439-type
    type(): cocoascript.NSEventType;
    setType(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1527726-subtype
    subtype(): cocoascript.NSEventSubtype;
    setSubtype(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1534405-modifierflags
    modifierFlags(): cocoascript.NSEventModifierFlags;
    setModifierFlags(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1524291-context
    context(): cocoascript.NSGraphicsContext;
    setContext(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1529068-locationinwindow
    locationInWindow(): cocoascript.NSPoint;
    setLocationInWindow(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1528239-timestamp
    timestamp(): cocoascript.NSTimeInterval;
    setTimestamp(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1530808-window
    window(): cocoascript.NSWindow;
    setWindow(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1531361-windownumber
    windowNumber(): cocoascript.NSInteger;
    setWindowNumber(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1525143-eventref
    eventRef(): void;
    setEventRef(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1530429-cgevent
    CGEvent(): cocoascript.CGEventRef;
    setCGEvent(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1535211-modifierflags
    modifierFlags(): cocoascript.NSEventModifierFlags;
    setModifierFlags(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1530832-keyrepeatdelay
    keyRepeatDelay(): cocoascript.NSTimeInterval;
    setKeyRepeatDelay(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1526076-keyrepeatinterval
    keyRepeatInterval(): cocoascript.NSTimeInterval;
    setKeyRepeatInterval(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1534183-characters
    characters(): cocoascript.NSString;
    setCharacters(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1524605-charactersignoringmodifiers
    charactersIgnoringModifiers(): cocoascript.NSString;
    setCharactersIgnoringModifiers(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1528049-arepeat
    ARepeat(): cocoascript.BOOL;
    setARepeat(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1534513-keycode
    keyCode(): cocoascript.short;
    setKeyCode(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1527943-pressedmousebuttons
    pressedMouseButtons(): cocoascript.NSUInteger;
    setPressedMouseButtons(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1528384-doubleclickinterval
    doubleClickInterval(): cocoascript.NSTimeInterval;
    setDoubleClickInterval(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1533380-mouselocation
    mouseLocation(): cocoascript.NSPoint;
    setMouseLocation(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1527828-buttonnumber
    buttonNumber(): cocoascript.NSInteger;
    setButtonNumber(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1528200-clickcount
    clickCount(): cocoascript.NSInteger;
    setClickCount(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1529610-associatedeventsmask
    associatedEventsMask(): cocoascript.NSEventMask;
    setAssociatedEventsMask(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1535220-eventnumber
    eventNumber(): cocoascript.NSInteger;
    setEventNumber(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1533974-trackingnumber
    trackingNumber(): cocoascript.NSInteger;
    setTrackingNumber(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1534800-trackingarea
    trackingArea(): cocoascript.NSTrackingArea;
    setTrackingArea(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1526810-userdata
    userData(): void;
    setUserData(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1528289-data1
    data1(): cocoascript.NSInteger;
    setData1(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1528647-data2
    data2(): cocoascript.NSInteger;
    setData2(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1534871-deltax
    deltaX(): cocoascript.CGFloat;
    setDeltaX(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1534158-deltay
    deltaY(): cocoascript.CGFloat;
    setDeltaY(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1531528-deltaz
    deltaZ(): cocoascript.CGFloat;
    setDeltaZ(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1534543-pressure
    pressure(): number;
    setPressure(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1527242-stage
    stage(): cocoascript.NSInteger;
    setStage(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1526739-stagetransition
    stageTransition(): cocoascript.CGFloat;
    setStageTransition(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1531392-pressurebehavior
    pressureBehavior(): cocoascript.NSPressureBehavior;
    setPressureBehavior(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1534648-capabilitymask
    capabilityMask(): cocoascript.NSUInteger;
    setCapabilityMask(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1530014-deviceid
    deviceID(): cocoascript.NSUInteger;
    setDeviceID(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1531702-enteringproximity
    enteringProximity(): cocoascript.BOOL;
    setEnteringProximity(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1528818-pointingdeviceid
    pointingDeviceID(): cocoascript.NSUInteger;
    setPointingDeviceID(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1533420-pointingdeviceserialnumber
    pointingDeviceSerialNumber(): cocoascript.NSUInteger;
    setPointingDeviceSerialNumber(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1535573-pointingdevicetype
    pointingDeviceType(): cocoascript.NSPointingDeviceType;
    setPointingDeviceType(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1528299-systemtabletid
    systemTabletID(): cocoascript.NSUInteger;
    setSystemTabletID(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1527003-tabletid
    tabletID(): cocoascript.NSUInteger;
    setTabletID(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1535813-uniqueid
    uniqueID(): number;
    setUniqueID(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1525177-vendorid
    vendorID(): cocoascript.NSUInteger;
    setVendorID(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1527736-vendorpointingdevicetype
    vendorPointingDeviceType(): cocoascript.NSUInteger;
    setVendorPointingDeviceType(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1530617-absolutex
    absoluteX(): cocoascript.NSInteger;
    setAbsoluteX(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1528904-absolutey
    absoluteY(): cocoascript.NSInteger;
    setAbsoluteY(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1532154-absolutez
    absoluteZ(): cocoascript.NSInteger;
    setAbsoluteZ(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1535428-buttonmask
    buttonMask(): cocoascript.NSEventButtonMask;
    setButtonMask(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1526249-rotation
    rotation(): number;
    setRotation(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1525959-tangentialpressure
    tangentialPressure(): number;
    setTangentialPressure(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1534226-tilt
    tilt(): cocoascript.NSPoint;
    setTilt(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1530551-vendordefined
    vendorDefined(): cocoascript.id;
    setVendorDefined(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1531642-magnification
    magnification(): cocoascript.CGFloat;
    setMagnification(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1530950-touchesmatchingphase
    touchesMatchingPhase_inView(phase: cocoascript.NSTouchPhase, view: cocoascript.NSView):cocoascript.NSTouch;
    // doc://com.apple.documentation/documentation/appkit/nsevent/2646917-alltouches
    allTouches():cocoascript.NSTouch;
    // doc://com.apple.documentation/documentation/appkit/nsevent/2646918-touchesforview
    touchesForView(view: cocoascript.NSView):cocoascript.NSTouch;
    // doc://com.apple.documentation/documentation/appkit/nsevent/2646916-coalescedtouchesfortouch
    coalescedTouchesForTouch(touch: cocoascript.NSTouch):cocoascript.NSTouch;
    // doc://com.apple.documentation/documentation/appkit/nsevent/2870068-mousecoalescingenabled
    mouseCoalescingEnabled(): cocoascript.BOOL;
    setMouseCoalescingEnabled(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1525758-hasprecisescrollingdeltas
    hasPreciseScrollingDeltas(): cocoascript.BOOL;
    setHasPreciseScrollingDeltas(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1524505-scrollingdeltax
    scrollingDeltaX(): cocoascript.CGFloat;
    setScrollingDeltaX(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1535387-scrollingdeltay
    scrollingDeltaY(): cocoascript.CGFloat;
    setScrollingDeltaY(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1525439-momentumphase
    momentumPhase(): cocoascript.NSEventPhase;
    setMomentumPhase(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1533550-phase
    phase(): cocoascript.NSEventPhase;
    setPhase(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/2870067-swipetrackingfromscrolleventsena
    swipeTrackingFromScrollEventsEnabled(): cocoascript.BOOL;
    setSwipeTrackingFromScrollEventsEnabled(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1533300-trackswipeeventwithoptions
    trackSwipeEventWithOptions_dampenAmountThresholdMin_max_usingHandler(options: cocoascript.NSEventSwipeTrackingOptions, minDampenThreshold: cocoascript.CGFloat, maxDampenThreshold: cocoascript.CGFloat, trackingHandler: cocoascript.BOOL):void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1525151-directioninvertedfromdevice
    directionInvertedFromDevice(): cocoascript.BOOL;
    setDirectionInvertedFromDevice(): void;
    // doc://com.apple.documentation/documentation/appkit/nsevent/1483105-locationinnode
    locationInNode(node: cocoascript.SKNode):cocoascript.CGPoint;
    // doc://com.apple.documentation/documentation/appkit/nsevent/3242717-charactersbyapplyingmodifiers
    charactersByApplyingModifiers(modifiers: cocoascript.NSEventModifierFlags):cocoascript.NSString;
    //
    alloc():cocoascript.NSEvent;
    //
    init():cocoascript.NSEvent;
  }
}

declare const NSEvent: cocoascript.NSEvent;
