declare namespace cocoascript {
  /**
   * doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding
   */
  interface NSStandardKeyBindingResponding extends NSObject {
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005196-canceloperation
    cancelOperation(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005197-capitalizeword
    capitalizeWord(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005198-centerselectioninvisiblearea
    centerSelectionInVisibleArea(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005199-changecaseofletter
    changeCaseOfLetter(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005200-complete
    complete(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005201-deletebackward
    deleteBackward(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005202-deletebackwardbydecomposingprevi
    deleteBackwardByDecomposingPreviousCharacter(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005203-deleteforward
    deleteForward(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005204-deletetobeginningofline
    deleteToBeginningOfLine(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005205-deletetobeginningofparagraph
    deleteToBeginningOfParagraph(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005206-deletetoendofline
    deleteToEndOfLine(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005207-deletetoendofparagraph
    deleteToEndOfParagraph(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005208-deletetomark
    deleteToMark(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005209-deletewordbackward
    deleteWordBackward(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005210-deletewordforward
    deleteWordForward(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005211-docommandbyselector
    doCommandBySelector(selector: cocoascript.SEL):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005212-indent
    indent(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005213-insertbacktab
    insertBacktab(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005214-insertcontainerbreak
    insertContainerBreak(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005215-insertdoublequoteignoringsubstit
    insertDoubleQuoteIgnoringSubstitution(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005216-insertlinebreak
    insertLineBreak(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005217-insertnewline
    insertNewline(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005218-insertnewlineignoringfieldeditor
    insertNewlineIgnoringFieldEditor(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005219-insertparagraphseparator
    insertParagraphSeparator(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005220-insertsinglequoteignoringsubstit
    insertSingleQuoteIgnoringSubstitution(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005221-inserttab
    insertTab(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005222-inserttabignoringfieldeditor
    insertTabIgnoringFieldEditor(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005223-inserttext
    insertText(insertString: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005224-lowercaseword
    lowercaseWord(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005225-makebasewritingdirectionlefttori
    makeBaseWritingDirectionLeftToRight(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005226-makebasewritingdirectionnatural
    makeBaseWritingDirectionNatural(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005227-makebasewritingdirectionrighttol
    makeBaseWritingDirectionRightToLeft(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005228-maketextwritingdirectionlefttori
    makeTextWritingDirectionLeftToRight(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005229-maketextwritingdirectionnatural
    makeTextWritingDirectionNatural(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005230-maketextwritingdirectionrighttol
    makeTextWritingDirectionRightToLeft(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005231-movebackward
    moveBackward(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005232-movebackwardandmodifyselection
    moveBackwardAndModifySelection(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005233-movedown
    moveDown(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005234-movedownandmodifyselection
    moveDownAndModifySelection(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005235-moveforward
    moveForward(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005236-moveforwardandmodifyselection
    moveForwardAndModifySelection(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005237-moveleft
    moveLeft(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005238-moveleftandmodifyselection
    moveLeftAndModifySelection(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005239-moveparagraphbackwardandmodifyse
    moveParagraphBackwardAndModifySelection(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005240-moveparagraphforwardandmodifysel
    moveParagraphForwardAndModifySelection(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005241-moveright
    moveRight(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005242-moverightandmodifyselection
    moveRightAndModifySelection(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005243-movetobeginningofdocument
    moveToBeginningOfDocument(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005244-movetobeginningofdocumentandmodi
    moveToBeginningOfDocumentAndModifySelection(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005245-movetobeginningofline
    moveToBeginningOfLine(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005246-movetobeginningoflineandmodifyse
    moveToBeginningOfLineAndModifySelection(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005247-movetobeginningofparagraph
    moveToBeginningOfParagraph(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005248-movetobeginningofparagraphandmod
    moveToBeginningOfParagraphAndModifySelection(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005249-movetoendofdocument
    moveToEndOfDocument(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005250-movetoendofdocumentandmodifysele
    moveToEndOfDocumentAndModifySelection(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005251-movetoendofline
    moveToEndOfLine(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005252-movetoendoflineandmodifyselectio
    moveToEndOfLineAndModifySelection(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005253-movetoendofparagraph
    moveToEndOfParagraph(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005254-movetoendofparagraphandmodifysel
    moveToEndOfParagraphAndModifySelection(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005255-movetoleftendofline
    moveToLeftEndOfLine(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005256-movetoleftendoflineandmodifysele
    moveToLeftEndOfLineAndModifySelection(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005257-movetorightendofline
    moveToRightEndOfLine(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005258-movetorightendoflineandmodifysel
    moveToRightEndOfLineAndModifySelection(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005259-moveup
    moveUp(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005260-moveupandmodifyselection
    moveUpAndModifySelection(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005261-movewordbackward
    moveWordBackward(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005262-movewordbackwardandmodifyselecti
    moveWordBackwardAndModifySelection(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005263-movewordforward
    moveWordForward(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005264-movewordforwardandmodifyselectio
    moveWordForwardAndModifySelection(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005265-movewordleft
    moveWordLeft(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005266-movewordleftandmodifyselection
    moveWordLeftAndModifySelection(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005267-movewordright
    moveWordRight(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005268-movewordrightandmodifyselection
    moveWordRightAndModifySelection(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005269-pagedown
    pageDown(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005270-pagedownandmodifyselection
    pageDownAndModifySelection(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005271-pageup
    pageUp(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005272-pageupandmodifyselection
    pageUpAndModifySelection(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005273-quicklookpreviewitems
    quickLookPreviewItems(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005274-scrolllinedown
    scrollLineDown(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005275-scrolllineup
    scrollLineUp(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005276-scrollpagedown
    scrollPageDown(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005277-scrollpageup
    scrollPageUp(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005278-scrolltobeginningofdocument
    scrollToBeginningOfDocument(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005279-scrolltoendofdocument
    scrollToEndOfDocument(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005280-selectall
    selectAll(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005281-selectline
    selectLine(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005282-selectparagraph
    selectParagraph(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005283-selecttomark
    selectToMark(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005284-selectword
    selectWord(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005285-setmark
    setMark(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005286-swapwithmark
    swapWithMark(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005287-transpose
    transpose(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005288-transposewords
    transposeWords(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005289-uppercaseword
    uppercaseWord(sender: cocoascript.NSStandardKeyBindingResponding):void;
    // doc://com.apple.documentation/documentation/appkit/nsstandardkeybindingresponding/3005290-yank
    yank(sender: cocoascript.NSStandardKeyBindingResponding):void;
  }
}
