declare namespace cocoascript {
/**
 * A window that an app displays on the screen.
 * doc://com.apple.documentation/documentation/appkit/nswindow
 */
interface NSWindow extends NSResponder {
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419477-initwithcontentrect
  initWithContentRect_styleMask_backing_defer(contentRect: cocoascript.NSRect, style: cocoascript.NSWindowStyleMask, backingStoreType: cocoascript.NSBackingStoreType, flag: cocoascript.BOOL):cocoascript.NSWindow;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419755-initwithcontentrect
  initWithContentRect_styleMask_backing_defer_screen(contentRect: cocoascript.NSRect, style: cocoascript.NSWindowStyleMask, backingStoreType: cocoascript.NSBackingStoreType, flag: cocoascript.BOOL, screen: cocoascript.NSScreen):cocoascript.NSWindow;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419060-delegate
  delegate(): cocoascript.NSWindowDelegate;
  setDelegate(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419615-contentviewcontroller
  contentViewController(): cocoascript.NSViewController;
  setContentViewController(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419160-contentview
  contentView(): cocoascript.NSView;
  setContentView(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419527-togglefullscreen
  toggleFullScreen(sender: cocoascript.NSWindow):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419220-workswhenmodal
  worksWhenModal(): cocoascript.BOOL;
  setWorksWhenModal(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419186-alphavalue
  alphaValue(): cocoascript.CGFloat;
  setAlphaValue(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419751-backgroundcolor
  backgroundColor(): cocoascript.NSColor;
  setBackgroundColor(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419569-colorspace
  colorSpace(): cocoascript.NSColorSpace;
  setColorSpace(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419725-canhide
  canHide(): cocoascript.BOOL;
  setCanHide(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419707-onactivespace
  onActiveSpace(): cocoascript.BOOL;
  setOnActiveSpace(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419777-hidesondeactivate
  hidesOnDeactivate(): cocoascript.BOOL;
  setHidesOnDeactivate(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419471-collectionbehavior
  collectionBehavior(): cocoascript.NSWindowCollectionBehavior;
  setCollectionBehavior(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419086-opaque
  opaque(): cocoascript.BOOL;
  setOpaque(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419234-hasshadow
  hasShadow(): cocoascript.BOOL;
  setHasShadow(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419529-invalidateshadow
  invalidateShadow():void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419356-autorecalculatescontentborderthi
  autorecalculatesContentBorderThicknessForEdge(edge: cocoascript.NSRectEdge):cocoascript.BOOL;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419218-setautorecalculatescontentborder
  setAutorecalculatesContentBorderThickness_forEdge(flag: cocoascript.BOOL, edge: cocoascript.NSRectEdge):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419775-contentborderthicknessforedge
  contentBorderThicknessForEdge(edge: cocoascript.NSRectEdge):cocoascript.CGFloat;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419541-setcontentborderthickness
  setContentBorderThickness_forEdge(thickness: cocoascript.CGFloat, edge: cocoascript.NSRectEdge):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419743-preventsapplicationterminationwh
  preventsApplicationTerminationWhenModal(): cocoascript.BOOL;
  setPreventsApplicationTerminationWhenModal(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419049-defaultdepthlimit
  defaultDepthLimit(): cocoascript.NSWindowDepth;
  setDefaultDepthLimit(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419068-windownumber
  windowNumber(): cocoascript.NSInteger;
  setWindowNumber(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419741-devicedescription
  deviceDescription(): cocoascript.id;
  setDeviceDescription(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419179-canbecomevisiblewithoutlogin
  canBecomeVisibleWithoutLogin(): cocoascript.BOOL;
  setCanBecomeVisibleWithoutLogin(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419729-sharingtype
  sharingType(): cocoascript.NSWindowSharingType;
  setSharingType(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419599-backingtype
  backingType(): cocoascript.NSBackingStoreType;
  setBackingType(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419613-depthlimit
  depthLimit(): cocoascript.NSWindowDepth;
  setDepthLimit(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419330-hasdynamicdepthlimit
  hasDynamicDepthLimit(): cocoascript.BOOL;
  setHasDynamicDepthLimit(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419108-contentrectforframerect
  contentRectForFrameRect(frameRect: cocoascript.NSRect):cocoascript.NSRect;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419134-framerectforcontentrect
  frameRectForContentRect(contentRect: cocoascript.NSRect):cocoascript.NSRect;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419092-windowcontroller
  windowController(): cocoascript.NSWindowController;
  setWindowController(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419467-attachedsheet
  attachedSheet(): cocoascript.NSWindow;
  setAttachedSheet(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419364-sheet
  sheet(): cocoascript.BOOL;
  setSheet(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419653-beginsheet
  beginSheet_completionHandler(sheetWindow: cocoascript.NSWindow, handler: cocoascript.NSModalResponse):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419198-begincriticalsheet
  beginCriticalSheet_completionHandler(sheetWindow: cocoascript.NSWindow, handler: cocoascript.NSModalResponse):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419318-endsheet
  endSheet(sheetWindow: cocoascript.NSWindow):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419497-endsheet
  endSheet_returnCode(sheetWindow: cocoascript.NSWindow, returnCode: cocoascript.NSModalResponse):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419052-sheetparent
  sheetParent(): cocoascript.NSWindow;
  setSheetParent(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419765-sheets
  sheets(): cocoascript.NSWindow;
  setSheets(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419697-frame
  frame(): cocoascript.NSRect;
  setFrame(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419690-setframeorigin
  setFrameOrigin(point: cocoascript.NSPoint):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419658-setframetopleftpoint
  setFrameTopLeftPoint(point: cocoascript.NSPoint):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419779-constrainframerect
  constrainFrameRect_toScreen(frameRect: cocoascript.NSRect, screen: cocoascript.NSScreen):cocoascript.NSRect;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419392-cascadetopleftfrompoint
  cascadeTopLeftFromPoint(topLeftPoint: cocoascript.NSPoint):cocoascript.NSPoint;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419753-setframe
  setFrame_display(frameRect: cocoascript.NSRect, flag: cocoascript.BOOL):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419519-setframe
  setFrame_display_animate(frameRect: cocoascript.NSRect, displayFlag: cocoascript.BOOL, animateFlag: cocoascript.BOOL):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419655-animationresizetime
  animationResizeTime(newFrame: cocoascript.NSRect):cocoascript.NSTimeInterval;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419507-aspectratio
  aspectRatio(): cocoascript.NSSize;
  setAspectRatio(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419206-minsize
  minSize(): cocoascript.NSSize;
  setMinSize(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419595-maxsize
  maxSize(): cocoascript.NSSize;
  setMaxSize(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419398-zoomed
  zoomed(): cocoascript.BOOL;
  setZoomed(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419450-performzoom
  performZoom(sender: cocoascript.NSWindow):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419513-zoom
  zoom(sender: cocoascript.NSWindow):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419302-resizeflags
  resizeFlags(): cocoascript.NSEventModifierFlags;
  setResizeFlags(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419390-resizeincrements
  resizeIncrements(): cocoascript.NSSize;
  setResizeIncrements(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419588-preservescontentduringliveresize
  preservesContentDuringLiveResize(): cocoascript.BOOL;
  setPreservesContentDuringLiveResize(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419378-inliveresize
  inLiveResize(): cocoascript.BOOL;
  setInLiveResize(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419148-contentaspectratio
  contentAspectRatio(): cocoascript.NSSize;
  setContentAspectRatio(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419670-contentminsize
  contentMinSize(): cocoascript.NSSize;
  setContentMinSize(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419100-setcontentsize
  setContentSize(size: cocoascript.NSSize):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419154-contentmaxsize
  contentMaxSize(): cocoascript.NSSize;
  setContentMaxSize(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419649-contentresizeincrements
  contentResizeIncrements(): cocoascript.NSSize;
  setContentResizeIncrements(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419094-contentlayoutguide
  contentLayoutGuide(): cocoascript.id;
  setContentLayoutGuide(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419124-contentlayoutrect
  contentLayoutRect(): cocoascript.NSRect;
  setContentLayoutRect(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419438-maxfullscreencontentsize
  maxFullScreenContentSize(): cocoascript.NSSize;
  setMaxFullScreenContentSize(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419627-minfullscreencontentsize
  minFullScreenContentSize(): cocoascript.NSSize;
  setMinFullScreenContentSize(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419660-orderout
  orderOut(sender: cocoascript.NSWindow):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419204-orderback
  orderBack(sender: cocoascript.NSWindow):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419495-orderfront
  orderFront(sender: cocoascript.NSWindow):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419444-orderfrontregardless
  orderFrontRegardless():void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419672-orderwindow
  orderWindow_relativeTo(place: cocoascript.NSWindowOrderingMode, otherWin: cocoascript.NSInteger):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419511-level
  level(): cocoascript.NSWindowLevel;
  setLevel(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419132-visible
  visible(): cocoascript.BOOL;
  setVisible(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419321-occlusionstate
  occlusionState(): cocoascript.NSWindowOcclusionState;
  setOcclusionState(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419723-setframeusingname
  setFrameUsingName(name: cocoascript.NSWindowFrameAutosaveName):cocoascript.BOOL;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419226-setframeusingname
  setFrameUsingName_force(name: cocoascript.NSWindowFrameAutosaveName, force: cocoascript.BOOL):cocoascript.BOOL;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419290-saveframeusingname
  saveFrameUsingName(name: cocoascript.NSWindowFrameAutosaveName):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419362-frameautosavename
  frameAutosaveName(): cocoascript.NSWindowFrameAutosaveName;
  setFrameAutosaveName(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419515-stringwithsavedframe
  stringWithSavedFrame(): cocoascript.NSWindowPersistableFrameDescriptor;
  setStringWithSavedFrame(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419759-setframefromstring
  setFrameFromString(string: cocoascript.NSWindowPersistableFrameDescriptor):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419735-keywindow
  keyWindow(): cocoascript.BOOL;
  setKeyWindow(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419543-canbecomekeywindow
  canBecomeKeyWindow(): cocoascript.BOOL;
  setCanBecomeKeyWindow(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419368-makekeywindow
  makeKeyWindow():void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419208-makekeyandorderfront
  makeKeyAndOrderFront(sender: cocoascript.NSWindow):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419338-becomekeywindow
  becomeKeyWindow():void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419047-resignkeywindow
  resignKeyWindow():void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419130-mainwindow
  mainWindow(): cocoascript.BOOL;
  setMainWindow(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419162-canbecomemainwindow
  canBecomeMainWindow(): cocoascript.BOOL;
  setCanBecomeMainWindow(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419271-makemainwindow
  makeMainWindow():void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419084-becomemainwindow
  becomeMainWindow():void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419212-resignmainwindow
  resignMainWindow():void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419731-toolbar
  toolbar(): cocoascript.NSToolbar;
  setToolbar(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419554-toggletoolbarshown
  toggleToolbarShown(sender: cocoascript.NSWindow):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419284-runtoolbarcustomizationpalette
  runToolbarCustomizationPalette(sender: cocoascript.NSWindow):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419236-childwindows
  childWindows(): cocoascript.NSWindow;
  setChildWindows(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419152-addchildwindow
  addChildWindow_ordered(childWin: cocoascript.NSWindow, place: cocoascript.NSWindowOrderingMode):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419063-removechildwindow
  removeChildWindow(childWin: cocoascript.NSWindow):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419695-parentwindow
  parentWindow(): cocoascript.NSWindow;
  setParentWindow(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419328-defaultbuttoncell
  defaultButtonCell(): cocoascript.NSButtonCell;
  setDefaultButtonCell(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419276-enablekeyequivalentfordefaultbut
  enableKeyEquivalentForDefaultButtonCell():void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419242-disablekeyequivalentfordefaultbu
  disableKeyEquivalentForDefaultButtonCell():void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419647-fieldeditor
  fieldEditor_forObject(createFlag: cocoascript.BOOL, object: cocoascript.NSWindow):cocoascript.NSText;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419469-endeditingfor
  endEditingFor(object: cocoascript.NSWindow):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419175-excludedfromwindowsmenu
  excludedFromWindowsMenu(): cocoascript.BOOL;
  setExcludedFromWindowsMenu(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419668-arecursorrectsenabled
  areCursorRectsEnabled(): cocoascript.BOOL;
  setAreCursorRectsEnabled(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419202-enablecursorrects
  enableCursorRects():void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419639-disablecursorrects
  disableCursorRects():void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419269-discardcursorrects
  discardCursorRects():void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419601-invalidatecursorrectsforview
  invalidateCursorRectsForView(view: cocoascript.NSView):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419464-resetcursorrects
  resetCursorRects():void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419491-standardwindowbutton
  standardWindowButton(b: cocoascript.NSWindowButton):cocoascript.NSButton;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419196-showstoolbarbutton
  showsToolbarButton(): cocoascript.BOOL;
  setShowsToolbarButton(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419167-titlebarappearstransparent
  titlebarAppearsTransparent(): cocoascript.BOOL;
  setTitlebarAppearsTransparent(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/3608199-toolbarstyle
  toolbarStyle(): cocoascript.NSWindowToolbarStyle;
  setToolbarStyle(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/3622489-titlebarseparatorstyle
  titlebarSeparatorStyle(): cocoascript.NSTitlebarSeparatorStyle;
  setTitlebarSeparatorStyle(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419382-addtitlebaraccessoryviewcontroll
  addTitlebarAccessoryViewController(childViewController: cocoascript.NSTitlebarAccessoryViewController):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419275-inserttitlebaraccessoryviewcontr
  insertTitlebarAccessoryViewController_atIndex(childViewController: cocoascript.NSTitlebarAccessoryViewController, index: cocoascript.NSInteger):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419643-removetitlebaraccessoryviewcontr
  removeTitlebarAccessoryViewControllerAtIndex(index: cocoascript.NSInteger):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419547-titlebaraccessoryviewcontrollers
  titlebarAccessoryViewControllers(): cocoascript.NSTitlebarAccessoryViewController;
  setTitlebarAccessoryViewControllers(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1646657-allowsautomaticwindowtabbing
  allowsAutomaticWindowTabbing(): cocoascript.BOOL;
  setAllowsAutomaticWindowTabbing(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1646658-usertabbingpreference
  userTabbingPreference(): cocoascript.NSWindowUserTabbingPreference;
  setUserTabbingPreference(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/2870102-tab
  tab(): cocoascript.NSWindowTab;
  setTab(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1644704-tabbingidentifier
  tabbingIdentifier(): cocoascript.NSWindowTabbingIdentifier;
  setTabbingIdentifier(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1855947-addtabbedwindow
  addTabbedWindow_ordered(window: cocoascript.NSWindow, ordered: cocoascript.NSWindowOrderingMode):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1644729-tabbingmode
  tabbingMode(): cocoascript.NSWindowTabbingMode;
  setTabbingMode(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1792044-tabbedwindows
  tabbedWindows(): cocoascript.NSWindow;
  setTabbedWindows(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1644693-selectnexttab
  selectNextTab(sender: cocoascript.NSWindow):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1644555-selectprevioustab
  selectPreviousTab(sender: cocoascript.NSWindow):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1644410-movetabtonewwindow
  moveTabToNewWindow(sender: cocoascript.NSWindow):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1644517-toggletabbar
  toggleTabBar(sender: cocoascript.NSWindow):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/2870175-toggletaboverview
  toggleTabOverview(sender: cocoascript.NSWindow):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/2879189-tabgroup
  tabGroup(): cocoascript.NSWindowTabGroup;
  setTabGroup(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419138-allowstooltipswhenapplicationisi
  allowsToolTipsWhenApplicationIsInactive(): cocoascript.BOOL;
  setAllowsToolTipsWhenApplicationIsInactive(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419298-currentevent
  currentEvent(): cocoascript.NSEvent;
  setCurrentEvent(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419304-nexteventmatchingmask
  nextEventMatchingMask(mask: cocoascript.NSEventMask):cocoascript.NSEvent;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419721-nexteventmatchingmask
  nextEventMatchingMask_untilDate_inMode_dequeue(mask: cocoascript.NSEventMask, expiration: cocoascript.NSDate, mode: cocoascript.NSRunLoopMode, deqFlag: cocoascript.BOOL):cocoascript.NSEvent;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419676-discardeventsmatchingmask
  discardEventsMatchingMask_beforeEvent(mask: cocoascript.NSEventMask, lastEvent: cocoascript.NSEvent):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419376-postevent
  postEvent_atStart(event: cocoascript.NSEvent, flag: cocoascript.BOOL):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419228-sendevent
  sendEvent(event: cocoascript.NSEvent):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419428-trytoperform
  tryToPerform_with(action: cocoascript.SEL, object: cocoascript.NSWindow):cocoascript.BOOL;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419479-initialfirstresponder
  initialFirstResponder(): cocoascript.NSView;
  setInitialFirstResponder(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419440-firstresponder
  firstResponder(): cocoascript.NSResponder;
  setFirstResponder(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419366-makefirstresponder
  makeFirstResponder(responder: cocoascript.NSResponder):cocoascript.BOOL;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419757-selectkeyviewprecedingview
  selectKeyViewPrecedingView(view: cocoascript.NSView):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419633-selectkeyviewfollowingview
  selectKeyViewFollowingView(view: cocoascript.NSView):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419110-selectpreviouskeyview
  selectPreviousKeyView(sender: cocoascript.NSWindow):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419715-selectnextkeyview
  selectNextKeyView(sender: cocoascript.NSWindow):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419158-keyviewselectiondirection
  keyViewSelectionDirection(): cocoascript.NSSelectionDirection;
  setKeyViewSelectionDirection(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419214-autorecalculateskeyviewloop
  autorecalculatesKeyViewLoop(): cocoascript.BOOL;
  setAutorecalculatesKeyViewLoop(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419350-recalculatekeyviewloop
  recalculateKeyViewLoop():void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419200-keydown
  keyDown(event: cocoascript.NSEvent):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419340-acceptsmousemovedevents
  acceptsMouseMovedEvents(): cocoascript.BOOL;
  setAcceptsMouseMovedEvents(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419354-ignoresmouseevents
  ignoresMouseEvents(): cocoascript.BOOL;
  setIgnoresMouseEvents(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419280-mouselocationoutsideofeventstrea
  mouseLocationOutsideOfEventStream(): cocoascript.NSPoint;
  setMouseLocationOutsideOfEventStream(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419727-trackeventsmatchingmask
  trackEventsMatchingMask_timeout_mode_handler(mask: cocoascript.NSEventMask, timeout: cocoascript.NSTimeInterval, mode: cocoascript.NSRunLoopMode, trackingHandler: cocoascript.BOOL):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419386-performwindowdragwithevent
  performWindowDragWithEvent(event: cocoascript.NSEvent):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1526255-restorable
  restorable(): cocoascript.BOOL;
  setRestorable(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1526241-restorationclass
  restorationClass(): cocoascript.NSWindowRestoration;
  setRestorationClass(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1526239-disablesnapshotrestoration
  disableSnapshotRestoration():void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1525288-enablesnapshotrestoration
  enableSnapshotRestoration():void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419358-display
  display():void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419096-displayifneeded
  displayIfNeeded():void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419609-viewsneeddisplay
  viewsNeedDisplay(): cocoascript.BOOL;
  setViewsNeedDisplay(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419300-allowsconcurrentviewdrawing
  allowsConcurrentViewDrawing(): cocoascript.BOOL;
  setAllowsConcurrentViewDrawing(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419763-animationbehavior
  animationBehavior(): cocoascript.NSWindowAnimationBehavior;
  setAnimationBehavior(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419483-disablescreenupdatesuntilflush
  disableScreenUpdatesUntilFlush():void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419577-update
  update():void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419224-dragimage
  dragImage_at_offset_event_pasteboard_source_slideBack(image: cocoascript.NSImage, baseLocation: cocoascript.NSPoint, initialOffset: cocoascript.NSSize, event: cocoascript.NSEvent, pboard: cocoascript.NSPasteboard, sourceObj: cocoascript.NSWindow, slideFlag: cocoascript.BOOL):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419140-registerfordraggedtypes
  registerForDraggedTypes(newTypes: cocoascript.NSPasteboardType):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419456-unregisterdraggedtypes
  unregisterDraggedTypes():void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419311-documentedited
  documentEdited(): cocoascript.BOOL;
  setDocumentEdited(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419459-backingscalefactor
  backingScaleFactor(): cocoascript.CGFloat;
  setBackingScaleFactor(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419319-backingalignedrect
  backingAlignedRect_options(rect: cocoascript.NSRect, options: cocoascript.NSAlignmentOptions):cocoascript.NSRect;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419273-convertrectfrombacking
  convertRectFromBacking(rect: cocoascript.NSRect):cocoascript.NSRect;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419260-convertrecttobacking
  convertRectToBacking(rect: cocoascript.NSRect):cocoascript.NSRect;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419286-convertrecttoscreen
  convertRectToScreen(rect: cocoascript.NSRect):cocoascript.NSRect;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419603-convertrectfromscreen
  convertRectFromScreen(rect: cocoascript.NSRect):cocoascript.NSRect;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419404-title
  title(): cocoascript.NSString;
  setTitle(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/3608198-subtitle
  subtitle(): cocoascript.NSString;
  setSubtitle(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419635-titlevisibility
  titleVisibility(): cocoascript.NSWindowTitleVisibility;
  setTitleVisibility(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419192-settitlewithrepresentedfilename
  setTitleWithRepresentedFilename(filename: cocoascript.NSString):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419631-representedfilename
  representedFilename(): cocoascript.NSString;
  setRepresentedFilename(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419066-representedurl
  representedURL(): cocoascript.NSURL;
  setRepresentedURL(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419232-screen
  screen(): cocoascript.NSScreen;
  setScreen(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419080-deepestscreen
  deepestScreen(): cocoascript.NSScreen;
  setDeepestScreen(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419430-displayswhenscreenprofilechanges
  displaysWhenScreenProfileChanges(): cocoascript.BOOL;
  setDisplaysWhenScreenProfileChanges(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419072-movablebywindowbackground
  movableByWindowBackground(): cocoascript.BOOL;
  setMovableByWindowBackground(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419579-movable
  movable(): cocoascript.BOOL;
  setMovable(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419090-center
  center():void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419288-performclose
  performClose(sender: cocoascript.NSWindow):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419662-close
  close():void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419062-releasedwhenclosed
  releasedWhenClosed(): cocoascript.BOOL;
  setReleasedWhenClosed(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419699-miniaturized
  miniaturized(): cocoascript.BOOL;
  setMiniaturized(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419749-performminiaturize
  performMiniaturize(sender: cocoascript.NSWindow):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419426-miniaturize
  miniaturize(sender: cocoascript.NSWindow):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419334-deminiaturize
  deminiaturize(sender: cocoascript.NSWindow):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419185-miniwindowimage
  miniwindowImage(): cocoascript.NSImage;
  setMiniwindowImage(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419571-miniwindowtitle
  miniwindowTitle(): cocoascript.NSString;
  setMiniwindowTitle(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419088-docktile
  dockTile(): cocoascript.NSDockTile;
  setDockTile(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419767-print
  print(sender: cocoascript.NSWindow):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419128-datawithepsinsiderect
  dataWithEPSInsideRect(rect: cocoascript.NSRect):cocoascript.NSData;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419418-datawithpdfinsiderect
  dataWithPDFInsideRect(rect: cocoascript.NSRect):cocoascript.NSData;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419454-validrequestorforsendtype
  validRequestorForSendType_returnType(sendType: cocoascript.NSPasteboardType, returnType: cocoascript.NSPasteboardType):cocoascript.NSWindow;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1526915-updateconstraintsifneeded
  updateConstraintsIfNeeded():void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1526910-layoutifneeded
  layoutIfNeeded():void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1526997-visualizeconstraints
  visualizeConstraints(constraints: cocoascript.NSLayoutConstraint):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1526957-anchorattributefororientation
  anchorAttributeForOrientation(orientation: cocoascript.NSLayoutConstraintOrientation):cocoascript.NSLayoutAttribute;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1526985-setanchorattribute
  setAnchorAttribute_forOrientation(attr: cocoascript.NSLayoutAttribute, orientation: cocoascript.NSLayoutConstraintOrientation):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419446-initwithwindowref
  initWithWindowRef(windowRef: void):cocoascript.NSWindow;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419485-windowref
  windowRef(): void;
  setWindowRef(): void;
  // doc://com.apple.documentation/documentation/appkit/1473812-nsbestdepth
  NSBestDepth(): cocoascript.BOOL;
  setNSBestDepth(): void;
  // doc://com.apple.documentation/documentation/appkit/1473660-nsbitsperpixelfromdepth
  NSBitsPerPixelFromDepth(): cocoascript.NSWindowDepth;
  setNSBitsPerPixelFromDepth(): void;
  // doc://com.apple.documentation/documentation/appkit/1473674-nsbitspersamplefromdepth
  NSBitsPerSampleFromDepth(): cocoascript.NSWindowDepth;
  setNSBitsPerSampleFromDepth(): void;
  // doc://com.apple.documentation/documentation/appkit/1473594-nscolorspacefromdepth
  NSColorSpaceFromDepth(): cocoascript.NSWindowDepth;
  setNSColorSpaceFromDepth(): void;
  // doc://com.apple.documentation/documentation/appkit/1473710-nsnumberofcolorcomponents
  NSNumberOfColorComponents(): cocoascript.NSColorSpaceName;
  setNSNumberOfColorComponents(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1449574-hasclosebox
  hasCloseBox(): cocoascript.BOOL;
  setHasCloseBox(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1449568-hastitlebar
  hasTitleBar(): cocoascript.BOOL;
  setHasTitleBar(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1449566-setisminiaturized
  setIsMiniaturized(flag: cocoascript.BOOL):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1449570-setisvisible
  setIsVisible(flag: cocoascript.BOOL):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1449589-setiszoomed
  setIsZoomed(flag: cocoascript.BOOL):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1449581-handleclosescriptcommand
  handleCloseScriptCommand(command: cocoascript.NSCloseCommand):cocoascript.NSWindow;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1449585-handleprintscriptcommand
  handlePrintScriptCommand(command: cocoascript.NSScriptCommand):cocoascript.NSWindow;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1449591-handlesavescriptcommand
  handleSaveScriptCommand(command: cocoascript.NSScriptCommand):cocoascript.NSWindow;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1449577-orderedindex
  orderedIndex(): cocoascript.NSInteger;
  setOrderedIndex(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindowdidbecomekeynotification
  NSWindowDidBecomeKeyNotification(): cocoascript.NSNotificationName;
  setNSWindowDidBecomeKeyNotification(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindowdidbecomemainnotification
  NSWindowDidBecomeMainNotification(): cocoascript.NSNotificationName;
  setNSWindowDidBecomeMainNotification(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindowdidchangescreennotification
  NSWindowDidChangeScreenNotification(): cocoascript.NSNotificationName;
  setNSWindowDidChangeScreenNotification(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindowdidchangescreenprofilenotification
  NSWindowDidChangeScreenProfileNotification(): cocoascript.NSNotificationName;
  setNSWindowDidChangeScreenProfileNotification(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindowdiddeminiaturizenotification
  NSWindowDidDeminiaturizeNotification(): cocoascript.NSNotificationName;
  setNSWindowDidDeminiaturizeNotification(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindowdidendsheetnotification
  NSWindowDidEndSheetNotification(): cocoascript.NSNotificationName;
  setNSWindowDidEndSheetNotification(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindowdidexposenotification
  NSWindowDidExposeNotification(): cocoascript.NSNotificationName;
  setNSWindowDidExposeNotification(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindowdidminiaturizenotification
  NSWindowDidMiniaturizeNotification(): cocoascript.NSNotificationName;
  setNSWindowDidMiniaturizeNotification(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindowdidmovenotification
  NSWindowDidMoveNotification(): cocoascript.NSNotificationName;
  setNSWindowDidMoveNotification(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindowdidresignkeynotification
  NSWindowDidResignKeyNotification(): cocoascript.NSNotificationName;
  setNSWindowDidResignKeyNotification(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindowdidresignmainnotification
  NSWindowDidResignMainNotification(): cocoascript.NSNotificationName;
  setNSWindowDidResignMainNotification(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindowdidresizenotification
  NSWindowDidResizeNotification(): cocoascript.NSNotificationName;
  setNSWindowDidResizeNotification(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindowdidupdatenotification
  NSWindowDidUpdateNotification(): cocoascript.NSNotificationName;
  setNSWindowDidUpdateNotification(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindowwillbeginsheetnotification
  NSWindowWillBeginSheetNotification(): cocoascript.NSNotificationName;
  setNSWindowWillBeginSheetNotification(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindowwillclosenotification
  NSWindowWillCloseNotification(): cocoascript.NSNotificationName;
  setNSWindowWillCloseNotification(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindowwillminiaturizenotification
  NSWindowWillMiniaturizeNotification(): cocoascript.NSNotificationName;
  setNSWindowWillMiniaturizeNotification(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindowwillmovenotification
  NSWindowWillMoveNotification(): cocoascript.NSNotificationName;
  setNSWindowWillMoveNotification(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/2998855-appearancesource
  appearanceSource(): cocoascript.NSAppearanceCustomization;
  setAppearanceSource(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1449579-floatingpanel
  floatingPanel(): cocoascript.BOOL;
  setFloatingPanel(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1449583-miniaturizable
  miniaturizable(): cocoascript.BOOL;
  setMiniaturizable(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1449576-modalpanel
  modalPanel(): cocoascript.BOOL;
  setModalPanel(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1449572-resizable
  resizable(): cocoascript.BOOL;
  setResizable(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419078-stylemask
  styleMask(): cocoascript.NSWindowStyleMask;
  setStyleMask(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1644535-windowtitlebarlayoutdirection
  windowTitlebarLayoutDirection(): cocoascript.NSUserInterfaceLayoutDirection;
  setWindowTitlebarLayoutDirection(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1449587-zoomable
  zoomable(): cocoascript.BOOL;
  setZoomable(): void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/2138278-canrepresentdisplaygamut
  canRepresentDisplayGamut(displayGamut: cocoascript.NSDisplayGamut):cocoascript.BOOL;
  // doc://com.apple.documentation/documentation/appkit/nswindow/2967180-convertpointfromscreen
  convertPointFromScreen(point: cocoascript.NSPoint):cocoascript.NSPoint;
  // doc://com.apple.documentation/documentation/appkit/nswindow/2967182-convertpointtoscreen
  convertPointToScreen(point: cocoascript.NSPoint):cocoascript.NSPoint;
  // doc://com.apple.documentation/documentation/appkit/nswindow/2967179-convertpointfrombacking
  convertPointFromBacking(point: cocoascript.NSPoint):cocoascript.NSPoint;
  // doc://com.apple.documentation/documentation/appkit/nswindow/2967181-convertpointtobacking
  convertPointToBacking(point: cocoascript.NSPoint):cocoascript.NSPoint;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1644639-mergeallwindows
  mergeAllWindows(sender: cocoascript.NSWindow):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419473-setdynamicdepthlimit
  setDynamicDepthLimit(flag: cocoascript.BOOL):void;
  // doc://com.apple.documentation/documentation/appkit/nswindow/1419509-setframeautosavename
  setFrameAutosaveName(name: cocoascript.NSWindowFrameAutosaveName):cocoascript.BOOL;
  // 
  alloc():cocoascript.NSWindow;
  // 
  init():cocoascript.NSWindow;
}
}
declare const NSWindow: cocoascript.NSWindow;

