declare namespace cocoascript {
  /**
   * doc://com.apple.documentation/documentation/iobluetooth/bluetoothenhancedsynchronousconnectioninfo
   */
  interface BluetoothEnhancedSynchronousConnectionInfo {
    // doc://com.apple.documentation/documentation/iobluetooth/bluetoothenhancedsynchronousconnectioninfo/1642930-inputbandwidth
    inputBandwidth(): cocoascript.BluetoothHCIInputBandwidth;
    setInputBandwidth(): void;
    // doc://com.apple.documentation/documentation/iobluetooth/bluetoothenhancedsynchronousconnectioninfo/1643028-inputcodeddatasize
    inputCodedDataSize(): cocoascript.BluetoothHCIInputCodedDataSize;
    setInputCodedDataSize(): void;
    // doc://com.apple.documentation/documentation/iobluetooth/bluetoothenhancedsynchronousconnectioninfo/1642916-inputcodingformat
    inputCodingFormat(): cocoascript.BluetoothHCIInputCodingFormat;
    setInputCodingFormat(): void;
    // doc://com.apple.documentation/documentation/iobluetooth/bluetoothenhancedsynchronousconnectioninfo/1642983-inputdatapath
    inputDataPath(): cocoascript.BluetoothHCIInputDataPath;
    setInputDataPath(): void;
    // doc://com.apple.documentation/documentation/iobluetooth/bluetoothenhancedsynchronousconnectioninfo/1643051-inputpcmdataformat
    inputPCMDataFormat(): cocoascript.BluetoothHCIInputPCMDataFormat;
    setInputPCMDataFormat(): void;
    // doc://com.apple.documentation/documentation/iobluetooth/bluetoothenhancedsynchronousconnectioninfo/1642982-inputpcmsampelpayloadmsbposition
    inputPCMSampelPayloadMSBPosition(): cocoascript.BluetoothHCIInputPCMSamplePayloadMSBPosition;
    setInputPCMSampelPayloadMSBPosition(): void;
    // doc://com.apple.documentation/documentation/iobluetooth/bluetoothenhancedsynchronousconnectioninfo/1643054-inputtransportunitsize
    inputTransportUnitSize(): cocoascript.BluetoothHCIInputTransportUnitSize;
    setInputTransportUnitSize(): void;
    // doc://com.apple.documentation/documentation/iobluetooth/bluetoothenhancedsynchronousconnectioninfo/1642959-maxlatency
    maxLatency(): cocoascript.BluetoothHCIMaxLatency;
    setMaxLatency(): void;
    // doc://com.apple.documentation/documentation/iobluetooth/bluetoothenhancedsynchronousconnectioninfo/1642939-outputbandwidth
    outputBandwidth(): cocoascript.BluetoothHCIOutputBandwidth;
    setOutputBandwidth(): void;
    // doc://com.apple.documentation/documentation/iobluetooth/bluetoothenhancedsynchronousconnectioninfo/1643017-outputcodeddatasize
    outputCodedDataSize(): cocoascript.BluetoothHCIOutputCodedDataSize;
    setOutputCodedDataSize(): void;
    // doc://com.apple.documentation/documentation/iobluetooth/bluetoothenhancedsynchronousconnectioninfo/1643011-outputcodingformat
    outputCodingFormat(): cocoascript.BluetoothHCIOutputCodingFormat;
    setOutputCodingFormat(): void;
    // doc://com.apple.documentation/documentation/iobluetooth/bluetoothenhancedsynchronousconnectioninfo/1642938-outputdatapath
    outputDataPath(): cocoascript.BluetoothHCIOutputDataPath;
    setOutputDataPath(): void;
    // doc://com.apple.documentation/documentation/iobluetooth/bluetoothenhancedsynchronousconnectioninfo/1642858-outputpcmdataformat
    outputPCMDataFormat(): cocoascript.BluetoothHCIOutputPCMDataFormat;
    setOutputPCMDataFormat(): void;
    // doc://com.apple.documentation/documentation/iobluetooth/bluetoothenhancedsynchronousconnectioninfo/1642842-outputpcmsampelpayloadmsbpositio
    outputPCMSampelPayloadMSBPosition(): cocoascript.BluetoothHCIOutputPCMSamplePayloadMSBPosition;
    setOutputPCMSampelPayloadMSBPosition(): void;
    // doc://com.apple.documentation/documentation/iobluetooth/bluetoothenhancedsynchronousconnectioninfo/1642840-outputtransportunitsize
    outputTransportUnitSize(): cocoascript.BluetoothHCIOutputTransportUnitSize;
    setOutputTransportUnitSize(): void;
    // doc://com.apple.documentation/documentation/iobluetooth/bluetoothenhancedsynchronousconnectioninfo/1643044-packettype
    packetType(): cocoascript.BluetoothPacketType;
    setPacketType(): void;
    // doc://com.apple.documentation/documentation/iobluetooth/bluetoothenhancedsynchronousconnectioninfo/1642941-receivebandwidth
    receiveBandWidth(): cocoascript.BluetoothHCIReceiveBandwidth;
    setReceiveBandWidth(): void;
    // doc://com.apple.documentation/documentation/iobluetooth/bluetoothenhancedsynchronousconnectioninfo/1643015-receivecodecframesize
    receiveCodecFrameSize(): cocoascript.BluetoothHCIReceiveCodecFrameSize;
    setReceiveCodecFrameSize(): void;
    // doc://com.apple.documentation/documentation/iobluetooth/bluetoothenhancedsynchronousconnectioninfo/1643022-receivecodingformat
    receiveCodingFormat(): cocoascript.BluetoothHCIReceiveCodingFormat;
    setReceiveCodingFormat(): void;
    // doc://com.apple.documentation/documentation/iobluetooth/bluetoothenhancedsynchronousconnectioninfo/1643041-retransmissioneffort
    retransmissionEffort(): cocoascript.BluetoothHCIRetransmissionEffort;
    setRetransmissionEffort(): void;
    // doc://com.apple.documentation/documentation/iobluetooth/bluetoothenhancedsynchronousconnectioninfo/1643037-transmitbandwidth
    transmitBandWidth(): cocoascript.BluetoothHCITransmitBandwidth;
    setTransmitBandWidth(): void;
    // doc://com.apple.documentation/documentation/iobluetooth/bluetoothenhancedsynchronousconnectioninfo/1642892-transmitcodecframesize
    transmitCodecFrameSize(): cocoascript.BluetoothHCITransmitCodecFrameSize;
    setTransmitCodecFrameSize(): void;
    // doc://com.apple.documentation/documentation/iobluetooth/bluetoothenhancedsynchronousconnectioninfo/1643075-transmitcodingformat
    transmitCodingFormat(): cocoascript.BluetoothHCITransmitCodingFormat;
    setTransmitCodingFormat(): void;
    // doc://com.apple.documentation/documentation/iobluetooth/bluetoothenhancedsynchronousconnectioninfo/1642866-voicesetting
    voiceSetting(): cocoascript.BluetoothHCIVoiceSetting;
    setVoiceSetting(): void;
  }
}
