declare namespace cocoascript {
/**
 * An image generated by a snapshotter object. 
 * doc://com.apple.documentation/documentation/mapkit/mkmapsnapshot
 */
interface MKMapSnapshot extends NSObject {
  // doc://com.apple.documentation/documentation/mapkit/mkmapsnapshot/1452701-image
  image(): cocoascript.UIImage;
  setImage(): void;
  // doc://com.apple.documentation/documentation/mapkit/mkmapsnapshot/3013837-appearance
  appearance(): cocoascript.NSAppearance;
  setAppearance(): void;
  // doc://com.apple.documentation/documentation/mapkit/mkmapsnapshot/1452523-pointforcoordinate
  pointForCoordinate(coordinate: cocoascript.CLLocationCoordinate2D):cocoascript.CGPoint;
  // doc://com.apple.documentation/documentation/mapkit/mkmapsnapshot/3152226-traitcollection
  traitCollection(): cocoascript.UITraitCollection;
  setTraitCollection(): void;
  // 
  alloc():cocoascript.MKMapSnapshot;
  // 
  init():cocoascript.MKMapSnapshot;
}
}
declare const MKMapSnapshot: cocoascript.MKMapSnapshot;

