declare namespace cocoascript {
/**
 * The metadata associated with a file.
 * doc://com.apple.documentation/documentation/foundation/nsmetadataitem
 */
interface NSMetadataItem extends NSObject {
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitem/1414919-initwithurl
  initWithURL(url: cocoascript.NSURL):cocoascript.NSMetadataItem;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitem/1418347-attributes
  attributes(): cocoascript.NSString;
  setAttributes(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitem/1411721-valueforattribute
  valueForAttribute(key: cocoascript.NSString):cocoascript.NSMetadataItem;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitem/1409934-valuesforattributes
  valuesForAttributes(keys: cocoascript.NSString):cocoascript.NSMetadataItem;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemaudienceskey
  NSMetadataItemAudiencesKey(): cocoascript.const;
  setNSMetadataItemAudiencesKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemaudiobitratekey
  NSMetadataItemAudioBitRateKey(): cocoascript.const;
  setNSMetadataItemAudioBitRateKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemaudiochannelcountkey
  NSMetadataItemAudioChannelCountKey(): cocoascript.const;
  setNSMetadataItemAudioChannelCountKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemaudioencodingapplicationkey
  NSMetadataItemAudioEncodingApplicationKey(): cocoascript.const;
  setNSMetadataItemAudioEncodingApplicationKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemaudiosampleratekey
  NSMetadataItemAudioSampleRateKey(): cocoascript.const;
  setNSMetadataItemAudioSampleRateKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemaudiotracknumberkey
  NSMetadataItemAudioTrackNumberKey(): cocoascript.const;
  setNSMetadataItemAudioTrackNumberKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemauthoraddresseskey
  NSMetadataItemAuthorAddressesKey(): cocoascript.const;
  setNSMetadataItemAuthorAddressesKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemauthoremailaddresseskey
  NSMetadataItemAuthorEmailAddressesKey(): cocoascript.const;
  setNSMetadataItemAuthorEmailAddressesKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemauthorskey
  NSMetadataItemAuthorsKey(): cocoascript.const;
  setNSMetadataItemAuthorsKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemacquisitionmakekey
  NSMetadataItemAcquisitionMakeKey(): cocoascript.const;
  setNSMetadataItemAcquisitionMakeKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemacquisitionmodelkey
  NSMetadataItemAcquisitionModelKey(): cocoascript.const;
  setNSMetadataItemAcquisitionModelKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemalbumkey
  NSMetadataItemAlbumKey(): cocoascript.const;
  setNSMetadataItemAlbumKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemaltitudekey
  NSMetadataItemAltitudeKey(): cocoascript.const;
  setNSMetadataItemAltitudeKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemaperturekey
  NSMetadataItemApertureKey(): cocoascript.const;
  setNSMetadataItemApertureKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemappleloopdescriptorskey
  NSMetadataItemAppleLoopDescriptorsKey(): cocoascript.const;
  setNSMetadataItemAppleLoopDescriptorsKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemappleloopskeyfiltertypekey
  NSMetadataItemAppleLoopsKeyFilterTypeKey(): cocoascript.const;
  setNSMetadataItemAppleLoopsKeyFilterTypeKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemappleloopsloopmodekey
  NSMetadataItemAppleLoopsLoopModeKey(): cocoascript.const;
  setNSMetadataItemAppleLoopsLoopModeKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemappleloopsrootkeykey
  NSMetadataItemAppleLoopsRootKeyKey(): cocoascript.const;
  setNSMetadataItemAppleLoopsRootKeyKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemapplicationcategorieskey
  NSMetadataItemApplicationCategoriesKey(): cocoascript.const;
  setNSMetadataItemApplicationCategoriesKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemattributechangedatekey
  NSMetadataItemAttributeChangeDateKey(): cocoascript.const;
  setNSMetadataItemAttributeChangeDateKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemfsnamekey
  NSMetadataItemFSNameKey(): cocoascript.const;
  setNSMetadataItemFSNameKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemdisplaynamekey
  NSMetadataItemDisplayNameKey(): cocoascript.const;
  setNSMetadataItemDisplayNameKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemurlkey
  NSMetadataItemURLKey(): cocoascript.const;
  setNSMetadataItemURLKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitempathkey
  NSMetadataItemPathKey(): cocoascript.const;
  setNSMetadataItemPathKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemfssizekey
  NSMetadataItemFSSizeKey(): cocoascript.const;
  setNSMetadataItemFSSizeKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemfscreationdatekey
  NSMetadataItemFSCreationDateKey(): cocoascript.const;
  setNSMetadataItemFSCreationDateKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemfscontentchangedatekey
  NSMetadataItemFSContentChangeDateKey(): cocoascript.const;
  setNSMetadataItemFSContentChangeDateKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitembitspersamplekey
  NSMetadataItemBitsPerSampleKey(): cocoascript.const;
  setNSMetadataItemBitsPerSampleKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemcfbundleidentifierkey
  NSMetadataItemCFBundleIdentifierKey(): cocoascript.const;
  setNSMetadataItemCFBundleIdentifierKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemcameraownerkey
  NSMetadataItemCameraOwnerKey(): cocoascript.const;
  setNSMetadataItemCameraOwnerKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemcitykey
  NSMetadataItemCityKey(): cocoascript.const;
  setNSMetadataItemCityKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemcodecskey
  NSMetadataItemCodecsKey(): cocoascript.const;
  setNSMetadataItemCodecsKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemcolorspacekey
  NSMetadataItemColorSpaceKey(): cocoascript.const;
  setNSMetadataItemColorSpaceKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemcommentkey
  NSMetadataItemCommentKey(): cocoascript.const;
  setNSMetadataItemCommentKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemcomposerkey
  NSMetadataItemComposerKey(): cocoascript.const;
  setNSMetadataItemComposerKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemcontactkeywordskey
  NSMetadataItemContactKeywordsKey(): cocoascript.const;
  setNSMetadataItemContactKeywordsKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemcontentcreationdatekey
  NSMetadataItemContentCreationDateKey(): cocoascript.const;
  setNSMetadataItemContentCreationDateKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemcontentmodificationdatekey
  NSMetadataItemContentModificationDateKey(): cocoascript.const;
  setNSMetadataItemContentModificationDateKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemcontenttypekey
  NSMetadataItemContentTypeKey(): cocoascript.const;
  setNSMetadataItemContentTypeKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemcontenttypetreekey
  NSMetadataItemContentTypeTreeKey(): cocoascript.const;
  setNSMetadataItemContentTypeTreeKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemcontributorskey
  NSMetadataItemContributorsKey(): cocoascript.const;
  setNSMetadataItemContributorsKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemcopyrightkey
  NSMetadataItemCopyrightKey(): cocoascript.const;
  setNSMetadataItemCopyrightKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemcountrykey
  NSMetadataItemCountryKey(): cocoascript.const;
  setNSMetadataItemCountryKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemcoveragekey
  NSMetadataItemCoverageKey(): cocoascript.const;
  setNSMetadataItemCoverageKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemcreatorkey
  NSMetadataItemCreatorKey(): cocoascript.const;
  setNSMetadataItemCreatorKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemdateaddedkey
  NSMetadataItemDateAddedKey(): cocoascript.const;
  setNSMetadataItemDateAddedKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemdeliverytypekey
  NSMetadataItemDeliveryTypeKey(): cocoascript.const;
  setNSMetadataItemDeliveryTypeKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemdescriptionkey
  NSMetadataItemDescriptionKey(): cocoascript.const;
  setNSMetadataItemDescriptionKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemdirectorkey
  NSMetadataItemDirectorKey(): cocoascript.const;
  setNSMetadataItemDirectorKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemdownloadeddatekey
  NSMetadataItemDownloadedDateKey(): cocoascript.const;
  setNSMetadataItemDownloadedDateKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemduedatekey
  NSMetadataItemDueDateKey(): cocoascript.const;
  setNSMetadataItemDueDateKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemdurationsecondskey
  NSMetadataItemDurationSecondsKey(): cocoascript.const;
  setNSMetadataItemDurationSecondsKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemexifgpsversionkey
  NSMetadataItemEXIFGPSVersionKey(): cocoascript.const;
  setNSMetadataItemEXIFGPSVersionKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemexifversionkey
  NSMetadataItemEXIFVersionKey(): cocoascript.const;
  setNSMetadataItemEXIFVersionKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemeditorskey
  NSMetadataItemEditorsKey(): cocoascript.const;
  setNSMetadataItemEditorsKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitememailaddresseskey
  NSMetadataItemEmailAddressesKey(): cocoascript.const;
  setNSMetadataItemEmailAddressesKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemencodingapplicationskey
  NSMetadataItemEncodingApplicationsKey(): cocoascript.const;
  setNSMetadataItemEncodingApplicationsKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemexecutablearchitectureskey
  NSMetadataItemExecutableArchitecturesKey(): cocoascript.const;
  setNSMetadataItemExecutableArchitecturesKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemexecutableplatformkey
  NSMetadataItemExecutablePlatformKey(): cocoascript.const;
  setNSMetadataItemExecutablePlatformKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemexposuremodekey
  NSMetadataItemExposureModeKey(): cocoascript.const;
  setNSMetadataItemExposureModeKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemexposureprogramkey
  NSMetadataItemExposureProgramKey(): cocoascript.const;
  setNSMetadataItemExposureProgramKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemexposuretimesecondskey
  NSMetadataItemExposureTimeSecondsKey(): cocoascript.const;
  setNSMetadataItemExposureTimeSecondsKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemexposuretimestringkey
  NSMetadataItemExposureTimeStringKey(): cocoascript.const;
  setNSMetadataItemExposureTimeStringKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemfnumberkey
  NSMetadataItemFNumberKey(): cocoascript.const;
  setNSMetadataItemFNumberKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemfindercommentkey
  NSMetadataItemFinderCommentKey(): cocoascript.const;
  setNSMetadataItemFinderCommentKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemflashonoffkey
  NSMetadataItemFlashOnOffKey(): cocoascript.const;
  setNSMetadataItemFlashOnOffKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemfocallength35mmkey
  NSMetadataItemFocalLength35mmKey(): cocoascript.const;
  setNSMetadataItemFocalLength35mmKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemfocallengthkey
  NSMetadataItemFocalLengthKey(): cocoascript.const;
  setNSMetadataItemFocalLengthKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemfontskey
  NSMetadataItemFontsKey(): cocoascript.const;
  setNSMetadataItemFontsKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemgpsareainformationkey
  NSMetadataItemGPSAreaInformationKey(): cocoascript.const;
  setNSMetadataItemGPSAreaInformationKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemgpsdopkey
  NSMetadataItemGPSDOPKey(): cocoascript.const;
  setNSMetadataItemGPSDOPKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemgpsdatestampkey
  NSMetadataItemGPSDateStampKey(): cocoascript.const;
  setNSMetadataItemGPSDateStampKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemgpsdestbearingkey
  NSMetadataItemGPSDestBearingKey(): cocoascript.const;
  setNSMetadataItemGPSDestBearingKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemgpsdestdistancekey
  NSMetadataItemGPSDestDistanceKey(): cocoascript.const;
  setNSMetadataItemGPSDestDistanceKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemgpsdestlatitudekey
  NSMetadataItemGPSDestLatitudeKey(): cocoascript.const;
  setNSMetadataItemGPSDestLatitudeKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemgpsdestlongitudekey
  NSMetadataItemGPSDestLongitudeKey(): cocoascript.const;
  setNSMetadataItemGPSDestLongitudeKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemgpsdifferentalkey
  NSMetadataItemGPSDifferentalKey(): cocoascript.const;
  setNSMetadataItemGPSDifferentalKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemgpsmapdatumkey
  NSMetadataItemGPSMapDatumKey(): cocoascript.const;
  setNSMetadataItemGPSMapDatumKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemgpsmeasuremodekey
  NSMetadataItemGPSMeasureModeKey(): cocoascript.const;
  setNSMetadataItemGPSMeasureModeKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemgpsprocessingmethodkey
  NSMetadataItemGPSProcessingMethodKey(): cocoascript.const;
  setNSMetadataItemGPSProcessingMethodKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemgpsstatuskey
  NSMetadataItemGPSStatusKey(): cocoascript.const;
  setNSMetadataItemGPSStatusKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemgpstrackkey
  NSMetadataItemGPSTrackKey(): cocoascript.const;
  setNSMetadataItemGPSTrackKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemgenrekey
  NSMetadataItemGenreKey(): cocoascript.const;
  setNSMetadataItemGenreKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemhasalphachannelkey
  NSMetadataItemHasAlphaChannelKey(): cocoascript.const;
  setNSMetadataItemHasAlphaChannelKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemheadlinekey
  NSMetadataItemHeadlineKey(): cocoascript.const;
  setNSMetadataItemHeadlineKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemisospeedkey
  NSMetadataItemISOSpeedKey(): cocoascript.const;
  setNSMetadataItemISOSpeedKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemidentifierkey
  NSMetadataItemIdentifierKey(): cocoascript.const;
  setNSMetadataItemIdentifierKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemimagedirectionkey
  NSMetadataItemImageDirectionKey(): cocoascript.const;
  setNSMetadataItemImageDirectionKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataiteminformationkey
  NSMetadataItemInformationKey(): cocoascript.const;
  setNSMetadataItemInformationKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataiteminstantmessageaddresseskey
  NSMetadataItemInstantMessageAddressesKey(): cocoascript.const;
  setNSMetadataItemInstantMessageAddressesKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataiteminstructionskey
  NSMetadataItemInstructionsKey(): cocoascript.const;
  setNSMetadataItemInstructionsKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemisapplicationmanagedkey
  NSMetadataItemIsApplicationManagedKey(): cocoascript.const;
  setNSMetadataItemIsApplicationManagedKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemisgeneralmidisequencekey
  NSMetadataItemIsGeneralMIDISequenceKey(): cocoascript.const;
  setNSMetadataItemIsGeneralMIDISequenceKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemislikelyjunkkey
  NSMetadataItemIsLikelyJunkKey(): cocoascript.const;
  setNSMetadataItemIsLikelyJunkKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemkeysignaturekey
  NSMetadataItemKeySignatureKey(): cocoascript.const;
  setNSMetadataItemKeySignatureKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemkeywordskey
  NSMetadataItemKeywordsKey(): cocoascript.const;
  setNSMetadataItemKeywordsKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemkindkey
  NSMetadataItemKindKey(): cocoascript.const;
  setNSMetadataItemKindKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemlanguageskey
  NSMetadataItemLanguagesKey(): cocoascript.const;
  setNSMetadataItemLanguagesKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemlastuseddatekey
  NSMetadataItemLastUsedDateKey(): cocoascript.const;
  setNSMetadataItemLastUsedDateKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemlatitudekey
  NSMetadataItemLatitudeKey(): cocoascript.const;
  setNSMetadataItemLatitudeKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemlayernameskey
  NSMetadataItemLayerNamesKey(): cocoascript.const;
  setNSMetadataItemLayerNamesKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemlensmodelkey
  NSMetadataItemLensModelKey(): cocoascript.const;
  setNSMetadataItemLensModelKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemlongitudekey
  NSMetadataItemLongitudeKey(): cocoascript.const;
  setNSMetadataItemLongitudeKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemlyricistkey
  NSMetadataItemLyricistKey(): cocoascript.const;
  setNSMetadataItemLyricistKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemmaxaperturekey
  NSMetadataItemMaxApertureKey(): cocoascript.const;
  setNSMetadataItemMaxApertureKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemmediatypeskey
  NSMetadataItemMediaTypesKey(): cocoascript.const;
  setNSMetadataItemMediaTypesKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemmeteringmodekey
  NSMetadataItemMeteringModeKey(): cocoascript.const;
  setNSMetadataItemMeteringModeKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemmusicalgenrekey
  NSMetadataItemMusicalGenreKey(): cocoascript.const;
  setNSMetadataItemMusicalGenreKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemmusicalinstrumentcategorykey
  NSMetadataItemMusicalInstrumentCategoryKey(): cocoascript.const;
  setNSMetadataItemMusicalInstrumentCategoryKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemmusicalinstrumentnamekey
  NSMetadataItemMusicalInstrumentNameKey(): cocoascript.const;
  setNSMetadataItemMusicalInstrumentNameKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemnamedlocationkey
  NSMetadataItemNamedLocationKey(): cocoascript.const;
  setNSMetadataItemNamedLocationKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemnumberofpageskey
  NSMetadataItemNumberOfPagesKey(): cocoascript.const;
  setNSMetadataItemNumberOfPagesKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemorganizationskey
  NSMetadataItemOrganizationsKey(): cocoascript.const;
  setNSMetadataItemOrganizationsKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemorientationkey
  NSMetadataItemOrientationKey(): cocoascript.const;
  setNSMetadataItemOrientationKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemoriginalformatkey
  NSMetadataItemOriginalFormatKey(): cocoascript.const;
  setNSMetadataItemOriginalFormatKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemoriginalsourcekey
  NSMetadataItemOriginalSourceKey(): cocoascript.const;
  setNSMetadataItemOriginalSourceKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitempageheightkey
  NSMetadataItemPageHeightKey(): cocoascript.const;
  setNSMetadataItemPageHeightKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitempagewidthkey
  NSMetadataItemPageWidthKey(): cocoascript.const;
  setNSMetadataItemPageWidthKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemparticipantskey
  NSMetadataItemParticipantsKey(): cocoascript.const;
  setNSMetadataItemParticipantsKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemperformerskey
  NSMetadataItemPerformersKey(): cocoascript.const;
  setNSMetadataItemPerformersKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemphonenumberskey
  NSMetadataItemPhoneNumbersKey(): cocoascript.const;
  setNSMetadataItemPhoneNumbersKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitempixelcountkey
  NSMetadataItemPixelCountKey(): cocoascript.const;
  setNSMetadataItemPixelCountKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitempixelheightkey
  NSMetadataItemPixelHeightKey(): cocoascript.const;
  setNSMetadataItemPixelHeightKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitempixelwidthkey
  NSMetadataItemPixelWidthKey(): cocoascript.const;
  setNSMetadataItemPixelWidthKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemproducerkey
  NSMetadataItemProducerKey(): cocoascript.const;
  setNSMetadataItemProducerKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemprofilenamekey
  NSMetadataItemProfileNameKey(): cocoascript.const;
  setNSMetadataItemProfileNameKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemprojectskey
  NSMetadataItemProjectsKey(): cocoascript.const;
  setNSMetadataItemProjectsKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitempublisherskey
  NSMetadataItemPublishersKey(): cocoascript.const;
  setNSMetadataItemPublishersKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemrecipientaddresseskey
  NSMetadataItemRecipientAddressesKey(): cocoascript.const;
  setNSMetadataItemRecipientAddressesKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemrecipientemailaddresseskey
  NSMetadataItemRecipientEmailAddressesKey(): cocoascript.const;
  setNSMetadataItemRecipientEmailAddressesKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemrecipientskey
  NSMetadataItemRecipientsKey(): cocoascript.const;
  setNSMetadataItemRecipientsKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemrecordingdatekey
  NSMetadataItemRecordingDateKey(): cocoascript.const;
  setNSMetadataItemRecordingDateKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemrecordingyearkey
  NSMetadataItemRecordingYearKey(): cocoascript.const;
  setNSMetadataItemRecordingYearKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemredeyeonoffkey
  NSMetadataItemRedEyeOnOffKey(): cocoascript.const;
  setNSMetadataItemRedEyeOnOffKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemresolutionheightdpikey
  NSMetadataItemResolutionHeightDPIKey(): cocoascript.const;
  setNSMetadataItemResolutionHeightDPIKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemresolutionwidthdpikey
  NSMetadataItemResolutionWidthDPIKey(): cocoascript.const;
  setNSMetadataItemResolutionWidthDPIKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemrightskey
  NSMetadataItemRightsKey(): cocoascript.const;
  setNSMetadataItemRightsKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemsecuritymethodkey
  NSMetadataItemSecurityMethodKey(): cocoascript.const;
  setNSMetadataItemSecurityMethodKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemspeedkey
  NSMetadataItemSpeedKey(): cocoascript.const;
  setNSMetadataItemSpeedKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemstarratingkey
  NSMetadataItemStarRatingKey(): cocoascript.const;
  setNSMetadataItemStarRatingKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemstateorprovincekey
  NSMetadataItemStateOrProvinceKey(): cocoascript.const;
  setNSMetadataItemStateOrProvinceKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemstreamablekey
  NSMetadataItemStreamableKey(): cocoascript.const;
  setNSMetadataItemStreamableKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemsubjectkey
  NSMetadataItemSubjectKey(): cocoascript.const;
  setNSMetadataItemSubjectKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemtempokey
  NSMetadataItemTempoKey(): cocoascript.const;
  setNSMetadataItemTempoKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemtextcontentkey
  NSMetadataItemTextContentKey(): cocoascript.const;
  setNSMetadataItemTextContentKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemthemekey
  NSMetadataItemThemeKey(): cocoascript.const;
  setNSMetadataItemThemeKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemtimesignaturekey
  NSMetadataItemTimeSignatureKey(): cocoascript.const;
  setNSMetadataItemTimeSignatureKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemtimestampkey
  NSMetadataItemTimestampKey(): cocoascript.const;
  setNSMetadataItemTimestampKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemtitlekey
  NSMetadataItemTitleKey(): cocoascript.const;
  setNSMetadataItemTitleKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemtotalbitratekey
  NSMetadataItemTotalBitRateKey(): cocoascript.const;
  setNSMetadataItemTotalBitRateKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemversionkey
  NSMetadataItemVersionKey(): cocoascript.const;
  setNSMetadataItemVersionKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemvideobitratekey
  NSMetadataItemVideoBitRateKey(): cocoascript.const;
  setNSMetadataItemVideoBitRateKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemwherefromskey
  NSMetadataItemWhereFromsKey(): cocoascript.const;
  setNSMetadataItemWhereFromsKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemwhitebalancekey
  NSMetadataItemWhiteBalanceKey(): cocoascript.const;
  setNSMetadataItemWhiteBalanceKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataitemisubiquitouskey
  NSMetadataItemIsUbiquitousKey(): cocoascript.const;
  setNSMetadataItemIsUbiquitousKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataubiquitousitemcontainerdisplaynamekey
  NSMetadataUbiquitousItemContainerDisplayNameKey(): cocoascript.const;
  setNSMetadataUbiquitousItemContainerDisplayNameKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataubiquitousitemdownloadrequestedkey
  NSMetadataUbiquitousItemDownloadRequestedKey(): cocoascript.const;
  setNSMetadataUbiquitousItemDownloadRequestedKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataubiquitousitemisexternaldocumentkey
  NSMetadataUbiquitousItemIsExternalDocumentKey(): cocoascript.const;
  setNSMetadataUbiquitousItemIsExternalDocumentKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataubiquitousitemurlinlocalcontainerkey
  NSMetadataUbiquitousItemURLInLocalContainerKey(): cocoascript.const;
  setNSMetadataUbiquitousItemURLInLocalContainerKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataubiquitousitemhasunresolvedconflictskey
  NSMetadataUbiquitousItemHasUnresolvedConflictsKey(): cocoascript.const;
  setNSMetadataUbiquitousItemHasUnresolvedConflictsKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataubiquitousitemisdownloadedkey
  NSMetadataUbiquitousItemIsDownloadedKey(): cocoascript.const;
  setNSMetadataUbiquitousItemIsDownloadedKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataubiquitousitemisdownloadingkey
  NSMetadataUbiquitousItemIsDownloadingKey(): cocoascript.const;
  setNSMetadataUbiquitousItemIsDownloadingKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataubiquitousitemisuploadedkey
  NSMetadataUbiquitousItemIsUploadedKey(): cocoascript.const;
  setNSMetadataUbiquitousItemIsUploadedKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataubiquitousitemisuploadingkey
  NSMetadataUbiquitousItemIsUploadingKey(): cocoascript.const;
  setNSMetadataUbiquitousItemIsUploadingKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataubiquitousitempercentdownloadedkey
  NSMetadataUbiquitousItemPercentDownloadedKey(): cocoascript.const;
  setNSMetadataUbiquitousItemPercentDownloadedKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataubiquitousitempercentuploadedkey
  NSMetadataUbiquitousItemPercentUploadedKey(): cocoascript.const;
  setNSMetadataUbiquitousItemPercentUploadedKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataubiquitousitemdownloadingstatuskey
  NSMetadataUbiquitousItemDownloadingStatusKey(): cocoascript.const;
  setNSMetadataUbiquitousItemDownloadingStatusKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataubiquitousitemdownloadingerrorkey
  NSMetadataUbiquitousItemDownloadingErrorKey(): cocoascript.const;
  setNSMetadataUbiquitousItemDownloadingErrorKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataubiquitousitemuploadingerrorkey
  NSMetadataUbiquitousItemUploadingErrorKey(): cocoascript.const;
  setNSMetadataUbiquitousItemUploadingErrorKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataubiquitousitemissharedkey
  NSMetadataUbiquitousItemIsSharedKey(): cocoascript.const;
  setNSMetadataUbiquitousItemIsSharedKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataubiquitousshareditemcurrentuserpermissionskey
  NSMetadataUbiquitousSharedItemCurrentUserPermissionsKey(): cocoascript.const;
  setNSMetadataUbiquitousSharedItemCurrentUserPermissionsKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataubiquitousshareditemcurrentuserrolekey
  NSMetadataUbiquitousSharedItemCurrentUserRoleKey(): cocoascript.const;
  setNSMetadataUbiquitousSharedItemCurrentUserRoleKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataubiquitousshareditemmostrecenteditornamecomponentskey
  NSMetadataUbiquitousSharedItemMostRecentEditorNameComponentsKey(): cocoascript.const;
  setNSMetadataUbiquitousSharedItemMostRecentEditorNameComponentsKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataubiquitousshareditemownernamecomponentskey
  NSMetadataUbiquitousSharedItemOwnerNameComponentsKey(): cocoascript.const;
  setNSMetadataUbiquitousSharedItemOwnerNameComponentsKey(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataubiquitousitemdownloadingstatuscurrent
  NSMetadataUbiquitousItemDownloadingStatusCurrent(): cocoascript.const;
  setNSMetadataUbiquitousItemDownloadingStatusCurrent(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataubiquitousitemdownloadingstatusdownloaded
  NSMetadataUbiquitousItemDownloadingStatusDownloaded(): cocoascript.const;
  setNSMetadataUbiquitousItemDownloadingStatusDownloaded(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataubiquitousitemdownloadingstatusnotdownloaded
  NSMetadataUbiquitousItemDownloadingStatusNotDownloaded(): cocoascript.const;
  setNSMetadataUbiquitousItemDownloadingStatusNotDownloaded(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataubiquitousshareditempermissionsreadonly
  NSMetadataUbiquitousSharedItemPermissionsReadOnly(): cocoascript.const;
  setNSMetadataUbiquitousSharedItemPermissionsReadOnly(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataubiquitousshareditempermissionsreadwrite
  NSMetadataUbiquitousSharedItemPermissionsReadWrite(): cocoascript.const;
  setNSMetadataUbiquitousSharedItemPermissionsReadWrite(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataubiquitousshareditemroleowner
  NSMetadataUbiquitousSharedItemRoleOwner(): cocoascript.const;
  setNSMetadataUbiquitousSharedItemRoleOwner(): void;
  // doc://com.apple.documentation/documentation/foundation/nsmetadataubiquitousshareditemroleparticipant
  NSMetadataUbiquitousSharedItemRoleParticipant(): cocoascript.const;
  setNSMetadataUbiquitousSharedItemRoleParticipant(): void;
  // 
  alloc():cocoascript.NSMetadataItem;
  // 
  init():cocoascript.NSMetadataItem;
}
}
declare const NSMetadataItem: cocoascript.NSMetadataItem;

