declare namespace cocoascript {
/**
 * A formatter that converts between numeric values and their textual representations.
 * doc://com.apple.documentation/documentation/foundation/nsnumberformatter
 */
interface NSNumberFormatter extends NSFormatter {
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1417642-formatterbehavior
  formatterBehavior(): cocoascript.NSNumberFormatterBehavior;
  setFormatterBehavior(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1416915-numberstyle
  numberStyle(): cocoascript.NSNumberFormatterStyle;
  setNumberStyle(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1410503-generatesdecimalnumbers
  generatesDecimalNumbers(): cocoascript.BOOL;
  setGeneratesDecimalNumbers(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1412588-getobjectvalue
  getObjectValue_forString_range_error(obj: cocoascript._Nullable, string: cocoascript.NSString, rangep: cocoascript.NSRange, error: cocoascript._Nullable):cocoascript.BOOL;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1408845-numberfromstring
  numberFromString(string: cocoascript.NSString):cocoascript.NSNumber;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1418046-stringfromnumber
  stringFromNumber(number: cocoascript.NSNumber):cocoascript.NSString;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1408133-localizesformat
  localizesFormat(): cocoascript.BOOL;
  setLocalizesFormat(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1416967-locale
  locale(): cocoascript.NSLocale;
  setLocale(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1415880-roundingbehavior
  roundingBehavior(): cocoascript.NSDecimalNumberHandler;
  setRoundingBehavior(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1412561-roundingincrement
  roundingIncrement(): cocoascript.NSNumber;
  setRoundingIncrement(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1411156-roundingmode
  roundingMode(): cocoascript.NSNumberFormatterRoundingMode;
  setRoundingMode(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1410052-minimumintegerdigits
  minimumIntegerDigits(): cocoascript.NSUInteger;
  setMinimumIntegerDigits(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1407284-maximumintegerdigits
  maximumIntegerDigits(): cocoascript.NSUInteger;
  setMaximumIntegerDigits(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1410459-minimumfractiondigits
  minimumFractionDigits(): cocoascript.NSUInteger;
  setMinimumFractionDigits(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1415364-maximumfractiondigits
  maximumFractionDigits(): cocoascript.NSUInteger;
  setMaximumFractionDigits(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1417793-usessignificantdigits
  usesSignificantDigits(): cocoascript.BOOL;
  setUsesSignificantDigits(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1410174-minimumsignificantdigits
  minimumSignificantDigits(): cocoascript.NSUInteger;
  setMinimumSignificantDigits(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1412008-maximumsignificantdigits
  maximumSignificantDigits(): cocoascript.NSUInteger;
  setMaximumSignificantDigits(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1410565-format
  format(): cocoascript.NSString;
  setFormat(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1408543-formattingcontext
  formattingContext(): cocoascript.NSFormattingContext;
  setFormattingContext(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1411919-formatwidth
  formatWidth(): cocoascript.NSUInteger;
  setFormatWidth(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1414039-negativeformat
  negativeFormat(): cocoascript.NSString;
  setNegativeFormat(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1410737-positiveformat
  positiveFormat(): cocoascript.NSString;
  setPositiveFormat(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1408601-multiplier
  multiplier(): cocoascript.NSNumber;
  setMultiplier(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1407789-percentsymbol
  percentSymbol(): cocoascript.NSString;
  setPercentSymbol(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1412399-permillsymbol
  perMillSymbol(): cocoascript.NSString;
  setPerMillSymbol(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1409416-minussign
  minusSign(): cocoascript.NSString;
  setMinusSign(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1416423-plussign
  plusSign(): cocoascript.NSString;
  setPlusSign(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1417223-exponentsymbol
  exponentSymbol(): cocoascript.NSString;
  setExponentSymbol(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1410405-zerosymbol
  zeroSymbol(): cocoascript.NSString;
  setZeroSymbol(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1412699-nilsymbol
  nilSymbol(): cocoascript.NSString;
  setNilSymbol(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1416993-notanumbersymbol
  notANumberSymbol(): cocoascript.NSString;
  setNotANumberSymbol(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1417968-negativeinfinitysymbol
  negativeInfinitySymbol(): cocoascript.NSString;
  setNegativeInfinitySymbol(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1412976-positiveinfinitysymbol
  positiveInfinitySymbol(): cocoascript.NSString;
  setPositiveInfinitySymbol(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1414668-currencysymbol
  currencySymbol(): cocoascript.NSString;
  setCurrencySymbol(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1410463-currencycode
  currencyCode(): cocoascript.NSString;
  setCurrencyCode(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1412755-internationalcurrencysymbol
  internationalCurrencySymbol(): cocoascript.NSString;
  setInternationalCurrencySymbol(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1416213-currencygroupingseparator
  currencyGroupingSeparator(): cocoascript.NSString;
  setCurrencyGroupingSeparator(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1414204-positiveprefix
  positivePrefix(): cocoascript.NSString;
  setPositivePrefix(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1415071-positivesuffix
  positiveSuffix(): cocoascript.NSString;
  setPositiveSuffix(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1408096-negativeprefix
  negativePrefix(): cocoascript.NSString;
  setNegativePrefix(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1413927-negativesuffix
  negativeSuffix(): cocoascript.NSString;
  setNegativeSuffix(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1414530-textattributesfornegativevalues
  textAttributesForNegativeValues(): cocoascript.id;
  setTextAttributesForNegativeValues(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1409563-textattributesforpositivevalues
  textAttributesForPositiveValues(): cocoascript.id;
  setTextAttributesForPositiveValues(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1415516-attributedstringforzero
  attributedStringForZero(): cocoascript.NSAttributedString;
  setAttributedStringForZero(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1415971-textattributesforzero
  textAttributesForZero(): cocoascript.id;
  setTextAttributesForZero(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1416184-attributedstringfornil
  attributedStringForNil(): cocoascript.NSAttributedString;
  setAttributedStringForNil(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1408943-textattributesfornil
  textAttributesForNil(): cocoascript.id;
  setTextAttributesForNil(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1416819-attributedstringfornotanumber
  attributedStringForNotANumber(): cocoascript.NSAttributedString;
  setAttributedStringForNotANumber(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1410959-textattributesfornotanumber
  textAttributesForNotANumber(): cocoascript.id;
  setTextAttributesForNotANumber(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1408176-textattributesforpositiveinfinit
  textAttributesForPositiveInfinity(): cocoascript.id;
  setTextAttributesForPositiveInfinity(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1410417-textattributesfornegativeinfinit
  textAttributesForNegativeInfinity(): cocoascript.id;
  setTextAttributesForNegativeInfinity(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1412157-groupingseparator
  groupingSeparator(): cocoascript.NSString;
  setGroupingSeparator(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1409880-usesgroupingseparator
  usesGroupingSeparator(): cocoascript.BOOL;
  setUsesGroupingSeparator(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1412771-thousandseparator
  thousandSeparator(): cocoascript.NSString;
  setThousandSeparator(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1416451-hasthousandseparators
  hasThousandSeparators(): cocoascript.BOOL;
  setHasThousandSeparators(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1408029-decimalseparator
  decimalSeparator(): cocoascript.NSString;
  setDecimalSeparator(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1408550-alwaysshowsdecimalseparator
  alwaysShowsDecimalSeparator(): cocoascript.BOOL;
  setAlwaysShowsDecimalSeparator(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1407247-currencydecimalseparator
  currencyDecimalSeparator(): cocoascript.NSString;
  setCurrencyDecimalSeparator(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1416167-groupingsize
  groupingSize(): cocoascript.NSUInteger;
  setGroupingSize(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1413348-secondarygroupingsize
  secondaryGroupingSize(): cocoascript.NSUInteger;
  setSecondaryGroupingSize(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1413690-paddingcharacter
  paddingCharacter(): cocoascript.NSString;
  setPaddingCharacter(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1411127-paddingposition
  paddingPosition(): cocoascript.NSNumberFormatterPadPosition;
  setPaddingPosition(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1416119-allowsfloats
  allowsFloats(): cocoascript.BOOL;
  setAllowsFloats(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1417228-minimum
  minimum(): cocoascript.NSNumber;
  setMinimum(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1417787-maximum
  maximum(): cocoascript.NSNumber;
  setMaximum(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1416953-lenient
  lenient(): cocoascript.BOOL;
  setLenient(): void;
  // doc://com.apple.documentation/documentation/foundation/nsnumberformatter/1412244-partialstringvalidationenabled
  partialStringValidationEnabled(): cocoascript.BOOL;
  setPartialStringValidationEnabled(): void;
  // 
  alloc():cocoascript.NSNumberFormatter;
  // 
  init():cocoascript.NSNumberFormatter;
}
}
declare const NSNumberFormatter: cocoascript.NSNumberFormatter;

